### ISSUE TITLE
Does not compile with 6.17

### ISSUE THREAD

**Issue by AdityaGarg8** [linux-apfs/linux-apfs-rw#102]
```
In file included from fs/apfs/btree.c:8:
fs/apfs/apfs.h:1065:60: error: ‘struct fileattr’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 1065 | extern int apfs_fileattr_get(struct dentry *dentry, struct fileattr *fa);
      |                                                            ^~~~~~~~
fs/apfs/apfs.h:1066:85: error: ‘struct fileattr’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 1066 | extern int apfs_fileattr_set(struct mnt_idmap *idmap, struct dentry *dentry, struct fileattr *fa);
      |                                                                                     ^~~~~~~~
cc1: all warnings being treated as errors
make[4]: *** [scripts/Makefile.build:287: fs/apfs/btree.o] Error 1
make[3]: *** [scripts/Makefile.build:556: fs/apfs] Error 2
make[2]: *** [scripts/Makefile.build:556: fs] Error 2
make[1]: *** [/home/runner/work/linux-t2-patches/linux-t2-patches/linux-6.17-rc5/Makefile:2011: .] Error 2
make: *** [Makefile:248: __sub-make] Error 2
```

I get this error with 6.17.

**Comment by Artoria2e5** [comment]
Also does not build with 6.16:
```
build flags: SHELL=/nix/store/q7sqwn7i6w2b67adw0bmix29pxg85x3w-bash-5.3p3/bin/bash CC=/nix/store/82kmz7r96navanrc2fgckh2bamiqrgsw-gcc-14.3.0/bin/gcc LD=/nix/store/c43ry7z24x3jhnjlj4gpay8a4g>
./genver.sh
make -C /nix/store/h5pp7d5yx2icb3zy3jf44smyh3bazqyv-linux-xanmod-6.16.6-dev/lib/modules/6.16.6-xanmod1/build M=/build/source
make[1]: Entering directory '/nix/store/h5pp7d5yx2icb3zy3jf44smyh3bazqyv-linux-xanmod-6.16.6-dev/lib/modules/6.16.6-xanmod1/build'
make[2]: Entering directory '/build/source'
  CC [M]  btree.o
  CC [M]  compress.o
compress.c: In function 'apfs_compress_read_folio':
compress.c:425:19: error: 'struct page' has no member named 'index'
  425 |         off = page->index << PAGE_SHIFT;
      |                   ^~
make[4]: *** [/nix/store/h5pp7d5yx2icb3zy3jf44smyh3bazqyv-linux-xanmod-6.16.6-dev/lib/modules/6.16.6-xanmod1/source/scripts/Makefile.build:287: compress.o] Error 1
make[3]: *** [/nix/store/h5pp7d5yx2icb3zy3jf44smyh3bazqyv-linux-xanmod-6.16.6-dev/lib/modules/6.16.6-xanmod1/source/Makefile:2008: .] Error 2
make[2]: *** [/nix/store/h5pp7d5yx2icb3zy3jf44smyh3bazqyv-linux-xanmod-6.16.6-dev/lib/modules/6.16.6-xanmod1/source/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/build/source'
make[1]: *** [/nix/store/h5pp7d5yx2icb3zy3jf44smyh3bazqyv-linux-xanmod-6.16.6-dev/lib/modules/6.16.6-xanmod1/source/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/nix/store/h5pp7d5yx2icb3zy3jf44smyh3bazqyv-linux-xanmod-6.16.6-dev/lib/modules/6.16.6-xanmod1/build'
make: *** [Makefile:23: default] Error 2
```

**Comment by eafer** [comment]
Thanks! This should be fixed now.
