### ISSUE TITLE
Does not compile on Linux 4.14.237 and lower

### ISSUE THREAD

**Issue by Luflosi** [linux-apfs/linux-apfs-rw#12]
While preparing to add this kernel module to NixOS, I tried to build it for all kernels in Nixpkgs and it failed for three kernel versions. The README states, that this is supposed to work with kernel version 4.9 or before but it fails to build on 4.4.273, 4.9.273 and 4.14.237. The error message for Linux 4.14.237 boils down to
```
/build/source/dir.c:652:2: error: implicit declaration of function 'discard_new_inode'
  652 |  discard_new_inode(inode);
      |  ^~~~~~~~~~~~~~~~~
```
and the error message for Linux 4.4.273 and 4.9.273:
```
   23 |  SB_RDONLY = MS_RDONLY;
      |  ^~~~~~~~~
/build/source/apfs.h:23:2: error: type defaults to 'int' in declaration of 'SB_RDONLY'
```
I don't really care about those kernels. You should decide if you want to fix this or not as I can of course just exclude building this module with those old kernels in Nixpkgs.
Please either fix the compilation or update the README.
As always, I'm happy to try to compile any patches you may develop.

**Comment by eafer** [comment]
Thanks. I guess I'll just drop support for those versions unless someone claims to need them. The thing with discard_new_inode() in particular looks messy to fix.

**Comment by BrainSlayer** [comment]
actually its very easy to fix with a small compat function 
`
static inline void discard_new_inode(struct inode *inode)
{
        unlock_new_inode(inode);
        iput(inode);
}

`

**Comment by eafer** [comment]
You are right of course, thanks. I'll try to fix this today, but I can't test it myself.

**Comment by Luflosi** [comment]
I can test it if you like.

**Comment by eafer** [comment]
That would be very useful, thank you. There is a lot of new code too, so I wouldn't be surprised if the build finds new reasons to fail.

**Comment by Luflosi** [comment]
I'll test it tomorrow.

**Comment by Luflosi** [comment]
4.4.276 and 4.9.276 fail to compile with
```
In file included from /build/source/apfs.h:15,
                 from /build/source/btree.c:8:
/build/source/apfs_raw.h:872:21: error: 'UUID_SIZE' undeclared here (not in a function); did you mean 'PUD_SIZE'?
  872 | /*48*/ char nx_uuid[UUID_SIZE];
      |                     ^~~~~~~~~
      |                     PUD_SIZE
```
and 4.14.240 and 4.19.198 fail to compile with
```
/build/source/xattr.c: In function 'apfs_delete_all_xattrs':
/build/source/xattr.c:369:2: error: implicit declaration of function 'lockdep_assert_held_write'; did you mean 'lockdep_assert_held_once'? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration^G-Werror=implicit-function-declaration8;;^G]
  369 |  lockdep_assert_held_write(&nxi->nx_big_sem);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~
      |  lockdep_assert_held_once
```

**Comment by BrainSlayer** [comment]
the other errors are newly introduced since the < 4.19 compatiblity was removed some days ago from the source. you need to revert some changes from the latest source. check the git history. you will quickly find out which commits caused it.

**Comment by eafer** [comment]
> so i dont know which revision you used for checking.

I only work with the 5.3 kernel; I didn't check any older versions. I don't really know who is using the module and how, so I just trust that they'll complain if I break anything. I'll start putting more care into that stuff once the module is past the experimental stage, but for now there are too many other problems.

@Luflosi Thanks for the testing! I pushed one more patch, hopefully this one will be enough.

**Comment by Luflosi** [comment]
Now 4.14.240 and 4.19.198 compile again but there is still a small issue with compiling for 4.4.276 and 4.9.276:
```
build/source/compress.c: In function 'apfs_compress_file_open':
/build/source/compress.c:50:13: error: implicit declaration of function 'kvmalloc'; did you mean 'kmalloc'? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration^G-Werror=implicit-function-declaration8;;^G]
   50 |   fd->buf = kvmalloc(APFS_COMPRESS_BLOCK, GFP_KERNEL);
      |             ^~~~~~~~
      |             kmalloc
/build/source/compress.c:50:11: warning: assignment to 'u8 *' {aka 'unsigned char *'} from 'int' makes pointer from integer without a cast [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wint-conversion^G-Wint-conversion8;;^G]
   50 |   fd->buf = kvmalloc(APFS_COMPRESS_BLOCK, GFP_KERNEL);
      |           ^
/build/source/compress.c:63:12: warning: assignment to 'void *' from 'int' makes pointer from integer without a cast [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wint-conversion^G-Wint-conversion8;;^G]
   63 |   fd->data = kvmalloc(res, GFP_KERNEL);
      |            ^
/build/source/compress.c:75:12: warning: assignment to 'void *' from 'int' makes pointer from integer without a cast [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wint-conversion^G-Wint-conversion8;;^G]   75 |   fd->data = kvmalloc(le64_to_cpu(fd->hdr.size), GFP_KERNEL);
      |            ^
/build/source/compress.c:86:7: warning: assignment to 'u8 *' {aka 'unsigned char *'} from 'int' makes pointer from integer without a cast [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wint-conversion^G-Wint-conversion8;;^G]
   86 |   tmp = kvmalloc(res, GFP_KERNEL);
      |       ^
```

**Comment by BrainSlayer** [comment]
kvmalloc is not available in 4.4 and 4.9 if i remember correct. but easy to fix anyway. a compat wrapper for kvmalloc and kvfree is simple
`static inline void *kvmalloc(size_t size, gfp_t flags)
{
        gfp_t kmalloc_flags = flags;
        void *ret;

        if ((flags & GFP_KERNEL) != GFP_KERNEL)
                return kmalloc(size, flags);

        if (size > PAGE_SIZE)
                kmalloc_flags |= __GFP_NOWARN | __GFP_NORETRY;

        ret = kmalloc(size, flags);
        if (ret || size < PAGE_SIZE)
                return ret;

        return vmalloc(size);
}


static void kvfree(const void *addr)
{
        if (is_vmalloc_addr(addr))
                vfree(addr);
        else
                kfree(addr);
}

`

**Comment by eafer** [comment]
Thanks! I just pushed that.

**Comment by BrainSlayer** [comment]
kvfree seem to be not required. its already available since 3.15

**Comment by Luflosi** [comment]
Unfortunately, this still doesn't compile.
Compilation on 4.4.276 fails with:
```
/build/source/dir.c:234:3: error: 'const struct file_operations' has no member named 'iterate_shared'
  234 |  .iterate_shared = apfs_readdir,
      |   ^~~~~~~~~~~~~~
/build/source/dir.c:234:20: warning: initialization of 'ssize_t (*)(struct file *, const char *, size_t,  loff_t *)' {aka 'long int (*)(struct file *, const char *, long unsigned int,  long long int *)'} from incompatible pointer type 'int (*)(struct file *, struct dir_context *)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types^G-Wincompatible-pointer-types8;;^G]
  234 |  .iterate_shared = apfs_readdir,
      |                    ^~~~~~~~~~~~
/build/source/dir.c:234:20: note: (near initialization for 'apfs_dir_operations.write')
/build/source/dir.c: In function 'apfs_build_dentry_val':
/build/source/dir.c:310:26: error: implicit declaration of function 'current_time'; did you mean 'current_fs_time'? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration^G-Werror=implicit-function-declaration8;;^G]
  310 |  struct timespec64 now = current_time(inode);
      |                          ^~~~~~~~~~~~
      |                          current_fs_time
/build/source/dir.c:310:26: error: invalid initializer
/build/source/dir.c: In function 'apfs_create_dentry':
/build/source/dir.c:579:38: error: incompatible types when assigning to type 'struct timespec' from type 'int'
  579 |  parent->i_mtime = parent->i_ctime = current_time(inode);
      |                                      ^~~~~~~~~~~~
/build/source/dir.c: In function '__apfs_link':
/build/source/dir.c:783:19: error: incompatible types when assigning to type 'struct timespec' from type 'int'
  783 |  inode->i_ctime = current_time(inode);
      |                   ^~~~~~~~~~~~
/build/source/dir.c: In function 'apfs_delete_dentry':
/build/source/dir.c:956:38: error: incompatible types when assigning to type 'struct timespec' from type 'int'
  956 |  parent->i_mtime = parent->i_ctime = current_time(parent);
      |                                      ^~~~~~~~~~~~
/build/source/dir.c: In function 'apfs_create_orphan_link':
/build/source/dir.c:1116:42: error: incompatible types when assigning to type 'struct timespec' from type 'int'
 1116 |  priv_dir->i_mtime = priv_dir->i_ctime = current_time(priv_dir);
      |                                          ^~~~~~~~~~~~
/build/source/dir.c: In function 'apfs_delete_orphan_link':
/build/source/dir.c:1166:42: error: incompatible types when assigning to type 'struct timespec' from type 'int'
 1166 |  priv_dir->i_mtime = priv_dir->i_ctime = current_time(priv_dir);
      |                                          ^~~~~~~~~~~~
```
And on 4.9.276 it fails with:
```
/build/source/inode.c:771:1: error: expected identifier or '(' before '{' token
  771 | {
      | ^
```

**Comment by eafer** [comment]
That patch is for the 4.9 issue. I don't think the module ever built on 4.4 because ->iterate_shared() didn't exist back then, and that was among the first things I implemented. The 4.9 or before thing in the readme just meant that it might be possible to build it on 4.8, for example.

**Comment by Luflosi** [comment]
Now 4.9.276 fails with:
```
/build/source/super.c: In function 'apfs_check_features':
/build/source/super.c:989:8: error: implicit declaration of function 'sb_rdonly' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration^G-Werror=implicit-function-declaration8;;^G]
  989 |   if (!sb_rdonly(sb)) {
      |        ^~~~~~~~~
/build/source/super.c: In function 'apfs_mount':
/build/source/super.c:1209:62: error: 'SB_NOSEC' undeclared (first use in this function); did you mean 'S_NOSEC'?
 1209 |  sb = sget(fs_type, apfs_test_super, apfs_set_super, flags | SB_NOSEC, sbi);
      |                                                              ^~~~~~~~
      |                                                              S_NOSEC
/build/source/super.c:1209:62: note: each undeclared identifier is reported only once for each function it appears in
/build/source/super.c:1227:45: error: 'SB_SILENT' undeclared (first use in this function); did you mean 'MS_SILENT'?
 1227 |   error = apfs_fill_super(sb, data, flags & SB_SILENT ? 1 : 0);
      |                                             ^~~~~~~~~
      |                                             MS_SILENT
/build/source/super.c:1230:18: error: 'SB_ACTIVE' undeclared (first use in this function); did you mean 'MS_ACTIVE'?
 1230 |   sb->s_flags |= SB_ACTIVE;
      |                  ^~~~~~~~~
      |                  MS_ACTIVE
```

**Comment by Luflosi** [comment]
That commit builds fine on all Linux kernels in Nixpkgs except for 4.4.278 🎉. I even wrote some small tests and used it to test APFS with all of the kernels. All of them seem to work.
@BrainSlayer Does everything work for you too?

**Comment by BrainSlayer** [comment]
@Luflosi sure. but i'm a skilled developer. i can port apfs to almost any kernel version i need so far. but i just use it on 4.9. so in worst case i do the dirty job required and modify it if needed. you can find the code in the dd-wrt svn repository

**Comment by Luflosi** [comment]
I meant if you can now use APFS as-is, without patches?
