### ISSUE TITLE
Module does not compile on 6.16

### ISSUE THREAD

**Issue by AdityaGarg8** [linux-apfs/linux-apfs-rw#99]
I get this error:

```
fs/apfs/compress.c: In function ‘apfs_compress_read_folio’:
fs/apfs/compress.c:425:19: error: ‘struct page’ has no member named ‘index’
  425 |         off = page->index << PAGE_SHIFT;
      |                   ^~
make[4]: *** [scripts/Makefile.build:287: fs/apfs/compress.o] Error 1
make[3]: *** [scripts/Makefile.build:554: fs/apfs] Error 2
make[2]: *** [scripts/Makefile.build:554: fs] Error 2
make[1]: *** [/home/runner/work/linux-t2-patches/linux-t2-patches/linux-6.16-rc4/Makefile:2003: .] Error 2
make: *** [Makefile:248: __sub-make] Error 2
```
