### ISSUE TITLE
Driver fails to compile on 6.11

### ISSUE THREAD

**Issue by AdityaGarg8** [linux-apfs/linux-apfs-rw#75]
```
fs/apfs/extents.c:11: error: "MAX" redefined [-Werror]
   11 | #define MAX(X, Y)       ((X) <= (Y) ? (Y) : (X))
      | 
In file included from ./include/linux/kernel.h:28,
                 from ./include/linux/cpumask.h:11,
                 from ./include/linux/smp.h:13,
                 from ./include/linux/lockdep.h:14,
                 from ./include/linux/spinlock.h:63,
                 from ./include/linux/wait.h:9,
                 from ./include/linux/wait_bit.h:8,
                 from ./include/linux/fs.h:6,
                 from ./include/linux/highmem.h:5,
                 from ./include/linux/bvec.h:10,
                 from ./include/linux/blk_types.h:10,
                 from ./include/linux/buffer_head.h:12,
                 from fs/apfs/extents.c:6:
./include/linux/minmax.h:330: note: this is the location of the previous definition
  330 | #define MAX(a,b) __cmp(max,a,b)
      | 
cc1: all warnings being treated as errors
make[4]: *** [scripts/Makefile.build:244: fs/apfs/extents.o] Error 1
make[3]: *** [scripts/Makefile.build:485: fs/apfs] Error 2
make[2]: *** [scripts/Makefile.build:485: fs] Error 2
make[1]: *** [/home/runner/work/linux-t2-patches/linux-t2-patches/linux-6.11-rc5/Makefile:1925: .] Error 2
make: *** [Makefile:224: __sub-make] Error 2
```

I get this

**Comment by eafer** [comment]
Thanks, this should be fixed in the development branch now.

**Comment by eafer** [comment]
I just made a release so I guess I can close this.
