### ISSUE TITLE
Failure to compile with 6.18

### ISSUE THREAD

**Issue by AdityaGarg8** [linux-apfs/linux-apfs-rw#107]
Hi

I am getting this error when I try to compile the driver on kernel 6.18-rc2

```
fs/apfs/dir.c: In function ‘apfs_build_sibling_val’:
fs/apfs/dir.c:429:30: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  429 |         struct qstr *qname = &dentry->d_name;
      |                              ^
fs/apfs/dir.c: In function ‘apfs_create_dentry’:
fs/apfs/dir.c:593:45: error: passing argument 2 of ‘apfs_create_dentry_rec’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  593 |         err = apfs_create_dentry_rec(inode, &dentry->d_name, apfs_ino(parent), sibling_id);
      |                                             ^~~~~~~~~~~~~~~
fs/apfs/dir.c:366:69: note: expected ‘struct qstr *’ but argument is of type ‘const struct qstr *’
  366 | static int apfs_create_dentry_rec(struct inode *inode, struct qstr *qname,
      |                                                        ~~~~~~~~~~~~~^~~~~
fs/apfs/dir.c: In function ‘apfs_prepare_dentry_for_link’:
fs/apfs/dir.c:811:56: error: passing argument 2 of ‘apfs_create_dentry_rec’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  811 |         return apfs_create_dentry_rec(d_inode(dentry), &dentry->d_name,
      |                                                        ^~~~~~~~~~~~~~~
fs/apfs/dir.c:366:69: note: expected ‘struct qstr *’ but argument is of type ‘const struct qstr *’
  366 | static int apfs_create_dentry_rec(struct inode *inode, struct qstr *qname,
      |                                                        ~~~~~~~~~~~~~^~~~~
cc1: all warnings being treated as errors
make[4]: *** [scripts/Makefile.build:287: fs/apfs/dir.o] Error 1
make[3]: *** [scripts/Makefile.build:556: fs/apfs] Error 2
make[2]: *** [scripts/Makefile.build:556: fs] Error 2
make[1]: *** [/home/runner/work/linux-t2-patches/linux-t2-patches/linux-6.18-rc2/Makefile:2010: .] Error 2
make: *** [Makefile:248: __sub-make] Error 2
```

**Comment by eafer** [comment]
Thanks! I just pushed a patch that should fix this. It was fairly simple this time.
